routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();
//Redirect to closed view
Route::middleware(['closed'])->group(function () {
	/*
	|--------------------------------------------------------------------------
	| HOME route
	|--------------------------------------------------------------------------
	|
	*/

	Route::get('/', 'HomeController@index')->name('home');


	Route::post('/search/show', 'HomeController@searchShow')->name('search.show');
	Route::post('/search', 'HomeController@search')->name('search');

	/*
	|--------------------------------------------------------------------------
	| Athletes Routes
	|--------------------------------------------------------------------------
	|
	*/
	Route::get('/athlete/{athlete}', 'AthleteController@show')->name('athlete.show');

	/*
	|--------------------------------------------------------------------------
	| Competitions Routes
	|--------------------------------------------------------------------------
	|
	*/
	Route::get('/competition/{competition}', 'CompetitionController@show')->name('competition.show');
	Route::get('/calendar', 'CompetitionController@showCalendar')->name('competition.calendar');

	/*
	|--------------------------------------------------------------------------
	| Clubs Routes
	|--------------------------------------------------------------------------
	|
	*/
	Route::get('/club/{club}', 'ClubController@show')->name('club.show');


	/*
	|--------------------------------------------------------------------------
	| Records Routes
	|--------------------------------------------------------------------------
	|
	*/
	/* GET events for national record form */
	Route::post('/records/nationals/history/events', 'RecordController@getEvents')->name('record.getEvents');
	Route::get('/records/nationals/history', 'RecordController@showNRsHistory')->name('record.showNRsHistory')->middleware('role:admin');
	Route::post('/records/nationals/history', 'RecordController@searchNRsHistory')->name('record.searchNRsHistory')->middleware('role:admin');
	Route::get('/records/nationals', 'RecordController@showNRs')->name('record.showNRs');
	Route::post('/records/nationals', 'RecordController@searchNRs')->name('record.searchNRs');


	/*
	|--------------------------------------------------------------------------
	| Top-List Routes
	|--------------------------------------------------------------------------
	|
	*/
	Route::get('/toplist', 'TopListController@show')->name('toplist.show');
	Route::post('/toplist', 'TopListController@search')->name('toplist.search');
	Route::post('/toplist/events', 'TopListController@getEvents')->name('toplist.getEvents');


	/*
	|--------------------------------------------------------------------------
	| Score-List Routes
	|--------------------------------------------------------------------------
	|
	*/
	Route::get('/scorelist', 'ScoreListController@show')->name('scorelist.show');
	Route::post('/scorelist', 'ScoreListController@search')->name('scorelist.search');


	/*
	|--------------------------------------------------------------------------
	| All-Time Performance Routes
	|--------------------------------------------------------------------------
	|
	*/
	Route::get('/alltime', 'AllTimeController@show')->name('alltime.show');
	Route::post('/alltime', 'AllTimeController@search')->name('alltime.search');
	Route::post('/alltime/events', 'AllTimeController@getEvents')->name('alltime.getEvents');

	/*
	|--------------------------------------------------------------------------
	| Contact us Routes
	|--------------------------------------------------------------------------
	|
	*/
	Route::get('/contact-us', 'ContactController@show')->name('contact.show');
	Route::post('/contact-us', 'ContactController@send')->name('contact.send');


	/*
	|--------------------------------------------------------------------------
	| ADMIN DASHBOARD Routes
	|--------------------------------------------------------------------------
	|	resource routes for CRUD
	|	all the controllers are in App/Dashboard
	*/

	//For admins and moderators
	Route::middleware(['auth','role:admin,moderator'])->group(function () {
		Route::get('dashboard', function () {
		    return view('dashboard/home');
		});
		Route::resource('dashboard/club', 'Dashboard\ClubCrudController', ['except' => ['show', 'destroy']]);
		Route::resource('dashboard/athlete', 'Dashboard\AthleteCrudController', ['except' => ['show', 'destroy']]);
		Route::resource('dashboard/series', 'Dashboard\SeriesCrudController', ['except' => ['show', 'destroy']]);
		Route::resource('dashboard/competition', 'Dashboard\CompetitionCrudController', ['except' => ['show', 'destroy']]);
		Route::resource('dashboard/result', 'Dashboard\ResultCrudController', ['except' => ['show']]);
		Route::resource('dashboard/image', 'Dashboard\ImageCrudController', ['except' => ['show', 'destroy']]);
		Route::resource('dashboard/video', 'Dashboard\VideoCrudController', ['except' => ['show', 'destroy']]);

		Route::post('/dashboard/result/events', 'Dashboard\ResultCrudController@getEvents')->name('results.getEvents');
		Route::post('/dashboard/result/dates', 'Dashboard\ResultCrudController@getDates')->name('results.getDates');

		Route::get('/dashboard/result/createRace', 'Dashboard\ResultCrudController@createRace')->name('result.createRace');
		Route::post('/dashboard/result/createRace', 'Dashboard\ResultCrudController@storeRace')->name('result.storeRace');

	});
	//For admins only
	Route::middleware(['auth','role:admin'])->group(function () {
		Route::resource('dashboard/events', 'Dashboard\EventCrudController', ['except' => ['show','destroy']]);
		Route::resource('dashboard/users', 'Dashboard\UserCrudController', ['except' => ['create','store','show']]);
		//PENDING AND PUBLISHING
		Route::get('dashboard/pending', 'Dashboard\PendingController@index')->name('pending.index');
		Route::post('dashboard/pending', 'Dashboard\PendingController@publish')->name('pending.publish');

		//COMMANDS
		Route::get('dashboard/commands', 'Dashboard\CommandController@index')->name('commands.index');
		Route::get('dashboard/commands/fixyearinathletes', 'Dashboard\CommandController@fixYearInAthletes')->name('commands.fixYearInAthletes');
		Route::get('dashboard/commands/fixageinresults', 'Dashboard\CommandController@fixAgeInResults')->name('commands.fixAgeInResults');
		Route::post('dashboard/commands/refreshrecordbyevent', 'Dashboard\CommandController@refreshRecordByEvent')->name('commands.refreshRecordByEvent');

	});
});

app/Competition.php
<?php

namespace App;


use Illuminate\Database\Eloquent\Model;
use App\Traits\Linkable;
use App\Traits\Statusable;

class Competition extends Model
{

    use Linkable;
    use Statusable;

    public function competition_series()
    {
      return $this->belongsToMany(CompetitionSeries::class);
    }

    public function results()
    {
        return $this->hasMany('App\Result')->published();
    }

    public function videos()
		{
			return $this->morphToMany('App\Video', 'videable');
		}

	   public function images()
	   {
		  return $this->morphToMany('App\Image', 'imageable');
	   }

     public function links()
     {
       return $this->morphMany('App\Link', 'linkable');
     }


    /*
    ** Returns a collection of all results of this competition
    ** partitioned based on events ($key = $event_id , $value= collection of $Results )
    */
    public function getAllResultsByEvent()
    {

      //Get all results of competition
      $results = $this->results->sortBy('position');

      //Find events in which athlete has results
      $events = $this->uniqueEvents($results);

      //create a collection with keys the event_id and values the Results
      $collection=collect([]);
      foreach($events as $event){
        $eventResults = $results->where('event_id',$event);
        $collection = $collection->put($event, $eventResults);
      }

      return $collection;
    }

        /*
    // Returns an array with all the unique events of the results
    */
    public function uniqueEvents($results)
    {
      $events = $results->mapWithKeys(function ($item) {
        return [$item['event_id']=>$item];
      })->keys();

      return $events->toArray();
    }


    /****************************************************/
    //    Search Scope
    /****************************************************/
    public function scopeSearch($query,$search){
      // split on 1+ whitespace & ignore empty (eg. trailing space)
      $searchValues = preg_split('/\s+/', $search, -1, PREG_SPLIT_NO_EMPTY);

      return $query->where(function ($q) use ($searchValues) {
        foreach ($searchValues as $value) {
          $q->orWhere('name', 'like', "%{$value}%")
          ->orWhere('city','like', "%{$value}%")
          ->orWhere('country','like', "%{$value}%");
        }
      })->orderBy('name','asc');
    }


}

app/Result.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Record;
use App\Age;
use Carbon\Carbon;
use App\Traits\Statusable;

class Result extends Model
{
    use Statusable;

    public function competition()
    {
        return $this->belongsTo('App\Competition');
    }

    public function athlete()
    {
        return $this->belongsTo('App\Athlete');
    }

    public function relayAthletes()
    {
      return $this->BelongsToMany('App\Athlete', 'relay_athletes', 'result_id', 'athlete_id');
    }

    public function event()
    {
        return $this->belongsTo('App\Event');
    }

    public function records()
    {
		  return $this->BelongsToMany('App\Record', 'result_record', 'result_id', 'record_id')->withTimestamps();
    }


    public function isHanded()
    {
      return substr($this->mark, -1)=="H";
    }

    public function getAgeCategory(): string  
    {
      return Age::getCategory($this->age);
    }

    public function getMarkstrAttribute(): string
    {
      if($this->event->isTrack() || $this->event->isRelay()){
        if(starts_with($this->mark, '00:00:0')){
          return str_replace_first('00:00:0', '', $this->mark);
        }elseif(starts_with($this->mark, '00:00:')){
          return str_replace_first('00:00:', '', $this->mark);
        }elseif(starts_with($this->mark, '00:0')){
          return str_replace_first('00:0', '', $this->mark);
        }elseif(starts_with($this->mark, '00:0')){
          return str_replace_first('00:', '', $this->mark);
        }elseif(starts_with($this->mark, '00:')){
          return str_replace_first('00:', '', $this->mark);
        }elseif(starts_with($this->mark, '0')){
          $tmp =  str_replace_first('0', '', $this->mark);
          return substr($tmp, 0, 7);
        }
      }
      return $this->mark;
    }

    public function setPb($event)
    {
      return $this->records()->attach(Record::where('acronym', 'PB')->first()->id, ['event_id' => $event->id]);

    }

    public function setSb($event)
    {
      return $this->records()->attach(Record::where('acronym', 'SB')->first()->id, ['event_id' => $event->id]);
    }

    public function setNR($event)
    {
      return $this->records()->attach(Record::where('acronym', 'NR')->first()->id, ['event_id' => $event->id]);

    }

    public function setNUR($event)
    {
      return $this->records()->attach(Record::where('acronym', 'NUR')->first()->id, ['event_id' => $event->id]);
    }

    public function setNJR($event)
    {
      return $this->records()->attach(Record::where('acronym', 'NJR')->first()->id, ['event_id' => $event->id]);
    }

    public function setNYR($event)
    {
      return $this->records()->attach(Record::where('acronym', 'NYR')->first()->id, ['event_id' => $event->id]);
    }

    public function setNU16R($event)
    {
      return $this->records()->attach(Record::where('acronym', 'NU16R')->first()->id, ['event_id' => $event->id]);
    }

    public function scopeYears($query)
    {
      $dates = $query->pluck('date')->sort()->unique();

      $years = collect([]);
      foreach($dates as $date){
        $years->push(Carbon::parse($date)->year);
      }

      return $years->unique();
    }

    public function scopeFromYear($query, $year)
    {
      return $query->whereYear('date', $year)->get();
    }

}

app/Http/Controllers/CompetitionController.php
<?php

namespace App\Http\Controllers;

use App\Competition;
use Illuminate\Http\Request;

class CompetitionController extends Controller
{
    public function show(Competition $competition)
    {

        if(!$competition->status){
        abort(404);
        }

    	$results = $competition->getAllResultsByEvent();
    	return view('competition.show')->with('competition',$competition)
    									->with('results',$results);
    }


    public function showCalendar()
    {
    	$competitions = Competition::all();
    	return view('competition.calendar')->with('competitions',$competitions);
    }


}

resources/views/competition/calendar.blade.php
@extends('layouts.app')

@section('styles')
<link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.1.0/fullcalendar.min.css' />

<style type="text/css">
    h1{
        color: white;
        font-weight: bold;
        margin-top: 40px;
        margin-bottom: 20px; 
        text-shadow: -0.5px 0 black, 0 0.5px black, 0.5px 0 black, 0 -0.5px black;
    }
    .image-back {
        background: url(https://static1.squarespace.com/static/586cf745d2b85773859477d2/58bfe2b217bffc3b2fcf9bcd/58c27cb2a5790ae22306e6f9/1491474923990/banner11.png) no-repeat center;
        background-size:100%;
        min-height: 150px;
        margin-bottom: 10px;
    }
</style>

@endsection

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="col-md-12 image-back">
                <h1>Ημερολόγιο Αγώνων</h1>
            </div>    
            <div id='calendar'></div>

        </div>
    </div>
</div>
@endsection



@section('scripts')
<script src="//code.jquery.com/jquery-1.11.3.min.js"></script>
<script src='https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.17.1/moment.min.js'></script>
<script src='https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.1.0/fullcalendar.min.js'></script>
<script>
    $(document).ready(function() {
        // page is now ready, initialize the calendar...

        $('#calendar').fullCalendar({
            // put your options and callbacks here
            header: {
                center: 'prev,next today',
                right: 'month,listMonth,listYear,'
            },
            views: {
                month: {
                    buttonText: 'Ημερολόγιο'
                },
                listYear: {
                    buttonText: 'Χρονιά'
                },
                listMonth:{
                    buttonText: 'Μήνας'
                }
            },
            events : [
                @foreach($competitions as $competition)
                {
                    title : '{{ $competition->name }}',
                    url : '{{ route('competition.show', $competition->id) }}',
                    start: "{{ $competition->date_start }}" + "T00:00:00",
                    end: "{{ $competition->date_finish }}" + "T23:59:00",
                    @if( \Carbon\Carbon::now() < $competition->date_start )
                        color  : '#15ACA0', // Blue for future event
                    @elseif (\Carbon\Carbon::now() > $competition->date_finish)
                        color  : '#D72533', // RED for finished
                    @else
                        color  : '#1FC54F', // GREEN for now running
                    @endif
                    
                },
                @endforeach
            ],
            displayEventTime: false

        })
    });
</script>
@endsection

resources/views/competition/show.blade.php
@extends('layouts.app')
@section('styles')

    <link href="{{ asset('/css/profiles/profile.css') }}" rel="stylesheet">
    <link href="{{ asset('/css/headings/heading-in-profile.css') }}" rel="stylesheet">
@endsection
@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="panel with-nav-tabs panel-default">
                <div class="panel-heading">
                        <!-- TABS List -->
                        <ul class="nav nav-tabs">
                            <li class="active"><a href="#tab1default" data-toggle="tab">Πληροφορίες & Αποτελέσματα</a></li>
                            <li><a href="#tab3default" data-toggle="tab">Φωτογραφίες</a></li>
                            <li><a href="#tab4default" data-toggle="tab">Βίντεο</a></li>
                        </ul>
                </div>
                <div class="panel-body">
                    <div class="tab-content">

                        <!-- ****************************************** -->
                        <!--                MAIN TAB                    -->
                        <!-- ****************************************** -->
                        <div class="tab-pane fade in active" id="tab1default">
                            <div class="row">
                                <div class="col-sm-6">
                                    <div class="well">
                                        <p><h1>{{$competition->name}}</h1></p>
                                        <p>
                                            <ul style="list-style: square;">
                                                
                                                @foreach($competition->competition_series as $series)
                                                    <li>
                                                        <h4>{{$series->name}}</h4>
                                                    </li>
                                                @endforeach
                                                
                                            </ul>
                                        </p>
                                        <p>
                                            <ul class="list-inline">
                                                <li class="list-inline-item seperator">{{date('d-M-Y', strtotime($competition->date_start))}} - {{date('d-M-Y', strtotime($competition->date_finish))}}
                                                </li>
                                                <li class="list-inline-item seperator">{{$competition->city}}</li>
                                                <li class="list-inline-item  seperator">{{$competition->country}}</li>
                                                <li class="list-inline-item">{{$competition->venue}}</li>
                                            </ul>
                                        </p>
                                        @foreach($competition->links as $link)
                                          <p><a href="{{$link->path}}" target="_blank">{{$link->name}}</a></p>
                                        @endforeach
                                    </div>
                                </div>
                                <div class="col-sm-6">
                                    <p>
                                        <img src="{{ $competition->picture }}" class="img-responsive center" style="max-width: auto; max-height: auto;">
                                    </p>
                                </div>
                            </div>

                            <!-- RESULTS -->
                            @if($competition->results->count()>0)
                            <div class="row">
                                <div class="col-sm-12">
                                    <div class="panel with-nav-tabs panel-default">
                                        <div class="panel-heading">
                                            <h2>Αποτελέσματα:</h2>
                                            <!-- Results TABS List -->
                                            <ul class="nav nav-tabs">
                                              <li class="dropdown">
                                                <a href="#" data-toggle="dropdown">Αγώνισμα<span class="caret"></span></a>
                                                <ul class="dropdown-menu" role="menu">
                                                    @foreach($results as $key => $value)
                                                        @if ($value->first()->event->gender == 'male')
                                                            <li><a href="#tab{{$key}}result" data-toggle="tab">ΑΝΔΡEΣ {{$value->first()->event->name}}</a></li>
                                                        @else
                                                            <li><a href="#tab{{$key}}result" data-toggle="tab">ΓΥΝΑΙΚEΣ {{$value->first()->event->name}}</a></li>
                                                        @endif
                                                    @endforeach
                                                </ul>
                                              </li>
                                            </ul>
                                        </div>
                                        <div class="panel-body">
                                            <div class="tab-content">

                                                @foreach($results as $key => $value)
                                                    <div class="tab-pane fade" id="tab{{$key}}result">

                                                        <h4><b>{{$value->first()->event->name}}  -  {{date('d-m-Y', strtotime($value->first()->date))}}</b></h4>

                                                        @foreach($value->keyby('race')->keys() as $heat)
                                                            <h4>{{$heat}}</h4>
                                                            <table class="table table-condensed table-responsive">
                                                                <thead>
                                                                    <tr>
                                                                        <th>Θέση</th>
                                                                        <th>Aθλητής</th>
                                                                        <th>Επίδοση</th>
                                                                        <th>Πόντοι</th>
                                                                        <th></th>
                                                                    </tr>
                                                                </thead>
                                                                <tbody id="myTable">
                                                                    @foreach($value->where('race',$heat) as $result)
                                                                        <tr>
                                                                            <td>{{$result->position}}</th>
                                                                            <td> <a href="/athlete/{{$result->athlete->id}}">{{$result->athlete->name}} </a></td>
                                                                            <th>{{$result->markstr}}</td>
                                                                            <td>{{$result->score}}</td>
                                                                            <td>
                                                                            @foreach($result->records as $record)
                                                                                {{$record->acronym}} &nbsp;
                                                                            @endforeach
                                                                            </td>
                                                                        </tr>

                                                                    @endforeach
                                                                </tbody>

                                                            </table>
                                                        @endforeach

                                                    </div>

                                                @endforeach
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                          @endif
                        </div>

                        <!-- ****************************************** -->
                        <!--              PHOTOS TAB                    -->
                        <!-- ****************************************** -->
                        <div class="tab-pane fade" id="tab3default">
                            <h3>Φωτογραφίες Αγώνα</h3>
                            @if($competition->images->first())
                                @include('gallery.images', ['var' => $competition])
                            @endif

                        </div>


                        <!-- ****************************************** -->
                        <!--              VIDEOS TAB                    -->
                        <!-- ****************************************** -->
                        <div class="tab-pane fade" id="tab4default">
                            <h3>Βίντεο Αγώνα</h3>
                            @if($competition->videos->first())
                                @include('gallery.videos', ['var' => $competition])
                            @endif

                        </div>


                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection