routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();
//Redirect to closed view
Route::middleware(['closed'])->group(function () {
	/*
	|--------------------------------------------------------------------------
	| HOME route
	|--------------------------------------------------------------------------
	|
	*/

	Route::get('/', 'HomeController@index')->name('home');


	Route::post('/search/show', 'HomeController@searchShow')->name('search.show');
	Route::post('/search', 'HomeController@search')->name('search');

	/*
	|--------------------------------------------------------------------------
	| Athletes Routes
	|--------------------------------------------------------------------------
	|
	*/
	Route::get('/athlete/{athlete}', 'AthleteController@show')->name('athlete.show');

	/*
	|--------------------------------------------------------------------------
	| Competitions Routes
	|--------------------------------------------------------------------------
	|
	*/
	Route::get('/competition/{competition}', 'CompetitionController@show')->name('competition.show');
	Route::get('/calendar', 'CompetitionController@showCalendar')->name('competition.calendar');

	/*
	|--------------------------------------------------------------------------
	| Clubs Routes
	|--------------------------------------------------------------------------
	|
	*/
	Route::get('/club/{club}', 'ClubController@show')->name('club.show');


	/*
	|--------------------------------------------------------------------------
	| Records Routes
	|--------------------------------------------------------------------------
	|
	*/
	/* GET events for national record form */
	Route::post('/records/nationals/history/events', 'RecordController@getEvents')->name('record.getEvents');
	Route::get('/records/nationals/history', 'RecordController@showNRsHistory')->name('record.showNRsHistory')->middleware('role:admin');
	Route::post('/records/nationals/history', 'RecordController@searchNRsHistory')->name('record.searchNRsHistory')->middleware('role:admin');
	Route::get('/records/nationals', 'RecordController@showNRs')->name('record.showNRs');
	Route::post('/records/nationals', 'RecordController@searchNRs')->name('record.searchNRs');


	/*
	|--------------------------------------------------------------------------
	| Top-List Routes
	|--------------------------------------------------------------------------
	|
	*/
	Route::get('/toplist', 'TopListController@show')->name('toplist.show');
	Route::post('/toplist', 'TopListController@search')->name('toplist.search');
	Route::post('/toplist/events', 'TopListController@getEvents')->name('toplist.getEvents');


	/*
	|--------------------------------------------------------------------------
	| Score-List Routes
	|--------------------------------------------------------------------------
	|
	*/
	Route::get('/scorelist', 'ScoreListController@show')->name('scorelist.show');
	Route::post('/scorelist', 'ScoreListController@search')->name('scorelist.search');


	/*
	|--------------------------------------------------------------------------
	| All-Time Performance Routes
	|--------------------------------------------------------------------------
	|
	*/
	Route::get('/alltime', 'AllTimeController@show')->name('alltime.show');
	Route::post('/alltime', 'AllTimeController@search')->name('alltime.search');
	Route::post('/alltime/events', 'AllTimeController@getEvents')->name('alltime.getEvents');

	/*
	|--------------------------------------------------------------------------
	| Contact us Routes
	|--------------------------------------------------------------------------
	|
	*/
	Route::get('/contact-us', 'ContactController@show')->name('contact.show');
	Route::post('/contact-us', 'ContactController@send')->name('contact.send');


	/*
	|--------------------------------------------------------------------------
	| ADMIN DASHBOARD Routes
	|--------------------------------------------------------------------------
	|	resource routes for CRUD
	|	all the controllers are in App/Dashboard
	*/

	//For admins and moderators
	Route::middleware(['auth','role:admin,moderator'])->group(function () {
		Route::get('dashboard', function () {
		    return view('dashboard/home');
		});
		Route::resource('dashboard/club', 'Dashboard\ClubCrudController', ['except' => ['show', 'destroy']]);
		Route::resource('dashboard/athlete', 'Dashboard\AthleteCrudController', ['except' => ['show', 'destroy']]);
		Route::resource('dashboard/series', 'Dashboard\SeriesCrudController', ['except' => ['show', 'destroy']]);
		Route::resource('dashboard/competition', 'Dashboard\CompetitionCrudController', ['except' => ['show', 'destroy']]);
		Route::resource('dashboard/result', 'Dashboard\ResultCrudController', ['except' => ['show']]);
		Route::resource('dashboard/image', 'Dashboard\ImageCrudController', ['except' => ['show', 'destroy']]);
		Route::resource('dashboard/video', 'Dashboard\VideoCrudController', ['except' => ['show', 'destroy']]);

		Route::post('/dashboard/result/events', 'Dashboard\ResultCrudController@getEvents')->name('results.getEvents');
		Route::post('/dashboard/result/dates', 'Dashboard\ResultCrudController@getDates')->name('results.getDates');

		Route::get('/dashboard/result/createRace', 'Dashboard\ResultCrudController@createRace')->name('result.createRace');
		Route::post('/dashboard/result/createRace', 'Dashboard\ResultCrudController@storeRace')->name('result.storeRace');

	});
	//For admins only
	Route::middleware(['auth','role:admin'])->group(function () {
		Route::resource('dashboard/events', 'Dashboard\EventCrudController', ['except' => ['show','destroy']]);
		Route::resource('dashboard/users', 'Dashboard\UserCrudController', ['except' => ['create','store','show']]);
		//PENDING AND PUBLISHING
		Route::get('dashboard/pending', 'Dashboard\PendingController@index')->name('pending.index');
		Route::post('dashboard/pending', 'Dashboard\PendingController@publish')->name('pending.publish');

		//COMMANDS
		Route::get('dashboard/commands', 'Dashboard\CommandController@index')->name('commands.index');
		Route::get('dashboard/commands/fixyearinathletes', 'Dashboard\CommandController@fixYearInAthletes')->name('commands.fixYearInAthletes');
		Route::get('dashboard/commands/fixageinresults', 'Dashboard\CommandController@fixAgeInResults')->name('commands.fixAgeInResults');
		Route::post('dashboard/commands/refreshrecordbyevent', 'Dashboard\CommandController@refreshRecordByEvent')->name('commands.refreshRecordByEvent');

	});
});

app/Http/Controllers/Dashboard/AthleteCrudController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Athlete;
use App\Club;
use App\Link;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class AthleteCrudController extends Controller
{

    private $form_rules = [
      'first_name' => 'required|string|max:255|min:1',
      'last_name' => 'required|string|max:255|min:1',
      'dob'  => 'date|nullable',
      'year' => '',
      'club_id' => 'integer|nullable',
      'gender' => 'string|required',
      'picture' => 'nullable|mimes:jpeg,bmp,png',

      'link_name.*' => 'required|string',
      'link_path.*' => 'required|string',
    ];

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //GET all the athletes
        $athletes = Athlete::all();

        return view('dashboard.athlete.index')->with('athletes',$athletes);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $clubs = Club::all(); //list of clubs for select field in create form

        return view('dashboard.athlete.create')->with('clubs',$clubs);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //VALIDATE DATA
        $this->validate($request, $this->form_rules);

        $athleteDB = Athlete::where([
                              'first_name' => $request->first_name,
                              'last_name' => $request->last_name,
                              'dob' => $request->dob,
                              'gender' => $request->gender
                            ])->get();

        if(!$athleteDB->isEmpty()){
          return redirect()->route('athlete.index')->withStatus("Athlete is already exist!");
        }

        //CREATE new Athlete instance
        $athlete = new Athlete;

        if($request->udob){
          $athlete->year = $request->year;
          $athlete->dob = null;
        }else{
          $athlete->dob = $request->dob;
          $athlete->year = (new \DateTime($request->dob))->format('Y');
        }

        $athlete->first_name = $request->first_name;
        $athlete->last_name = $request->last_name;
        $athlete->club_id = $request->club_id;
        $athlete->gender = $request->gender;

        if (!empty($request['picture'])) {
            $picture = $request['picture']->store('pictures/athletes');
        }else{
            $picture = '/img/athlete.png';
        }
        $athlete->picture = $picture;

        $athlete->save();

        Link::store($athlete, $request->link_name, $request->link_path);

        return redirect()->route('athlete.index')->withStatus("Athlete stored!");

    }


    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $athlete=Athlete::find($id);
        $clubs = Club::all(); //list of clubs for select field in form

        return view('dashboard.athlete.edit')->with('clubs',$clubs)->with('athlete',$athlete);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

        $this->validate($request, $this->form_rules);


        $athlete = Athlete::find($id);

        $athlete->first_name = $request->first_name;
        $athlete->last_name = $request->last_name;
        $athlete->club_id = $request->club_id;
        $athlete->gender = $request->gender;

        if($request->udob){
          $athlete->year = $request->year;
          $athlete->dob = null;
        }else{
          $athlete->dob = $request->dob;
          $athlete->year = (new \DateTime($request->dob))->format('Y');
        }

        if (!empty($request['picture'])) {
            $picture = $request['picture']->store('pictures/athletes');
            $athlete->picture = $picture;
        }

        $athlete->save();

        Link::edit($athlete, $request->link_name, $request->link_path);

        return redirect()->route('athlete.index')->withStatus("Athlete updated!");;

    }


}

app/Http/Controllers/Dashboard/ClubCrudController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Club;
use App\Link;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Storage;

class ClubCrudController extends Controller
{

  private $form_rules = [
    'name' => 'required|string|max:255|min:1',
    'acronym' => 'required|string|max:10',
    'city'  => 'required|string|max:255|min:1',
    'since' => 'nullable|integer|min:1800|max:2017',
    'picture' => 'nullable|mimes:jpeg,bmp,png',

    'link_name.*' => 'required|string',
    'link_path.*' => 'required|string',
  ];

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //GET all the clubs
        $clubs = Club::all();

        return view('dashboard.club.index')->with('clubs',$clubs);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('dashboard.club.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $this->validate($request, $this->form_rules);


        $club = new Club;

        $club->name = $request->name;
        $club->acronym = $request->acronym;
        $club->city = $request->city;
        $club->since = $request->since;

        if (!empty($request->picture)) {
            $picture = '/storage/'.$request['picture']->store('pictures/clubs');
        }else{
            $picture = '/img/club.png';
        }
        $club->picture = $picture;

        $club->save();

        Link::store($club, $request->link_name, $request->link_path);

        return redirect()->route('club.index');

    }


    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $club=Club::find($id);
        return view('dashboard.club.edit')->with('club',$club);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

        request()->validate($this->form_rules);

        $club=Club::find($id);

        $club->name = $request->name;
        $club->acronym = $request->acronym;
        $club->city = $request->city;
        $club->since = $request->since;

        if (!empty($request['picture'])) {
            if($club->picture != '/img/club.png' ){
                Storage::delete(str_replace_first('/storage/', '', $club->picture));
            }
            $picture = '/storage/'.$request['picture']->store('pictures/clubs');
            $club->picture = $picture;
        }


        $club->save();

        Link::edit($club, $request->link_name, $request->link_path);

        return redirect()->route('club.index');

    }

}

app/Http/Controllers/Dashboard/CommandController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Athlete;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Event;
use App\Result;

class CommandController extends Controller
{
        /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
      $events = Event::all();

        return view('dashboard.commands.index')->withEvents($events);
    }

    /**
     * Fix year collumn in athletes that only have DOB
     *
     * @return \Illuminate\Http\Response
     */
    public function fixYearInAthletes($athletes = null)
    {
    	// Touto en se periptwsi pou theloume na perasoume sigkekrimenous athlites sto mellon
    	if($athletes === null){
   			$athletes = Athlete::where('dob','!=',null)->get();
    	}

   		foreach ($athletes as $athlete) {
        	$athlete->year = (new \DateTime($athlete->dob))->format('Y');
        	$athlete->save();
   		}
        return redirect()->route('commands.index')->withStatus("Athletes Year Collumn updated!");
    }

    public function refreshRecordByEvent()
    {

      $eventId = request()->event;

      if($eventId=="all"){
        $events = Event::all();
        foreach($events as $event){
          $event->refreshRecords();
        }
      }else{
        $event = Event::find($eventId);

        $event->refreshRecords();
      }


      return redirect()->route('commands.index')->withStatus("Event Records was updated!");
    }

    public function fixAgeInResults()
    {
      $results = Result::all();

      foreach($results as $result){
        //
        //Find and store age category
        //
        // 1. Get athlete DOB
        $athlete = Athlete::find($result->athlete->id);
        // 2. Find difference between DOB and result date YEAR
        $result_year = (new \DateTime($result->date))->format('Y');//year of result
        $dob_year = $athlete->year;//year of birth
        $difference = $result_year-$dob_year;
        // 3. Save age category in years format to result record
        $result->age = $difference;

        $result->save();
      }

      return redirect()->route('commands.index')->withStatus("Age Column for Result was updated!");

    }

}

resources/views/dashboard/events/create.blade.php
@extends('layouts.dashboard')

@section('content')
    <p><u><h4>Add New Event</h4></u></p>
    {!! Form::open(
        array(
            'route' => 'events.store',
            'class' => 'form-horizontal')
        )
    !!}

    {{ csrf_field() }}

        <!--Name input field-->
        <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
            <label for="name" class="col-md-4 control-label">Name</label>
            <div class="col-md-6">
                <input id="name" type="text" class="form-control" name="name" value="{{ old('name') }}" required autofocus>

                @if ($errors->has('name'))
                    <span class="help-block">
                        <strong>{{ $errors->first('name') }}</strong>
                    </span>
                @endif
            </div>
        </div>

        <!--Season input filed-->
        <div class="form-group{{ $errors->has('season') ? ' has-error' : '' }}">
            <label for="season" class="col-md-4 control-label">Season</label>
            <div class="col-md-6">
                {{ Form::select('season', [ 'outdoor' => 'Outdoor','indoor' => 'Indoor','cross country' => 'Cross Country'] )}}
                @if ($errors->has('season'))
                    <span class="help-block">
                        <strong>{{ $errors->first('season') }}</strong>
                    </span>
                @endif
            </div>
        </div>

        <!--Type input filed-->
        <div class="form-group{{ $errors->has('type') ? ' has-error' : '' }}">
            <label for="type" class="col-md-4 control-label">Type</label>
            <div class="col-md-6">
                {{ Form::select('type', [ 'track' => 'track','field' => 'Field','relay' => 'Relay'] )}}
                @if ($errors->has('type'))
                    <span class="help-block">
                        <strong>{{ $errors->first('type') }}</strong>
                    </span>
                @endif
            </div>
        </div>

        <!--Gender input filed-->
        <div class="form-group{{ $errors->has('gender') ? ' has-error' : '' }}">
            <label for="gender" class="col-md-4 control-label">Gender</label>
            <div class="col-md-6">
                {{ Form::select('gender', [ 'male' => 'Male','female' => 'Female'] )}}
                @if ($errors->has('gender'))
                    <span class="help-block">
                        <strong>{{ $errors->first('gender') }}</strong>
                    </span>
                @endif
            </div>
        </div>


        <!--Order input filed-->
        <div class="form-group{{ $errors->has('order') ? ' has-error' : '' }}">
            <label for="order" class="col-md-4 control-label">Order</label>
            <div class="col-md-6">
                <input id="order" type="text" class="form-control" name="order" value="{{ old('order') }}">
                @if ($errors->has('order'))
                    <span class="help-block">
                        <strong>{{ $errors->first('order') }}</strong>
                    </span>
                @endif
            </div>
        </div>


        <div class="form-group">

            <div class="col-md-2 col-md-offset-4">
                <a class="btn btn-outline-primary" href="{{ route('events.index') }}">Cancel</a>
            </div>
            <div class="col-md-2">
                <button type="submit" class="btn btn-primary">
                    Save Event
                </button>
            </div>
        </div>


    {!! Form::close() !!}



@endsection

resources/views/dashboard/events/edit.blade.php
@extends('layouts.dashboard')

@section('content')
    <p><u><h4>Edit Athlete</h4></u></p>

    {!! Form::model($event, ['route' => ['events.update',$event->id],'class'=>'form-horizontal']) !!}

        {{ Form::token() }}
        {{ method_field('PATCH') }}

        <!--Name input field-->
        <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
            <label for="name" class="col-md-4 control-label">Name</label>
            <div class="col-md-6">
                {{ Form::text('name',null,["class"=> 'form-control'])}}


                @if ($errors->has('name'))
                    <span class="help-block">
                        <strong>{{ $errors->first('name') }}</strong>
                    </span>
                @endif
            </div>
        </div>

        <!--Season input filed-->
        <div class="form-group{{ $errors->has('season') ? ' has-error' : '' }}">
            <label for="season" class="col-md-4 control-label">Season</label>
            <div class="col-md-6">
                {{ Form::select('season', [ 'outdoor' => 'Outdoor','indoor' => 'Indoor','cross country' => 'Cross Country'] )}}
                @if ($errors->has('season'))
                    <span class="help-block">
                        <strong>{{ $errors->first('season') }}</strong>
                    </span>
                @endif
            </div>
        </div>

        <!--Type input filed-->
        <div class="form-group{{ $errors->has('type') ? ' has-error' : '' }}">
            <label for="type" class="col-md-4 control-label">Type</label>
            <div class="col-md-6">
                {{ Form::select('type', [ 'track' => 'track','field' => 'Field','relay' => 'Relay'] )}}
                @if ($errors->has('type'))
                    <span class="help-block">
                        <strong>{{ $errors->first('type') }}</strong>
                    </span>
                @endif
            </div>
        </div>

        <!--Gender input filed-->
        <div class="form-group{{ $errors->has('gender') ? ' has-error' : '' }}">
            <label for="gender" class="col-md-4 control-label">Gender</label>
            <div class="col-md-6">
                {{ Form::select('gender', [ 'male' => 'Male','female' => 'Female'] )}}
                @if ($errors->has('gender'))
                    <span class="help-block">
                        <strong>{{ $errors->first('gender') }}</strong>
                    </span>
                @endif
            </div>
        </div>

        <!--Order input filed-->
        <div class="form-group{{ $errors->has('order') ? ' has-error' : '' }}">
            <label for="order" class="col-md-4 control-label">Order</label>
            <div class="col-md-6">
                {{ Form::text('order',null,["class"=> 'form-control'])}}
                @if ($errors->has('order'))
                    <span class="help-block">
                        <strong>{{ $errors->first('order') }}</strong>
                    </span>
                @endif
            </div>
        </div>


        <div class="form-group">

            <div class="col-md-2 col-md-offset-4">
                <a class="btn btn-outline-primary" href="{{ route('events.index') }}">Cancel</a>
            </div>
            <div class="col-md-2">
                <button type="submit" class="btn btn-primary">
                    Save Event
                </button>
            </div>
        </div>


    {!! Form::close() !!}
@endsection

resources/views/dashboard/events/index.blade.php
@extends('layouts.dashboard')

@section('content')

	@if (session('status'))
	<div class="alert alert-success">
	<strong>{{ session('status') }}</strong>
	</div>
	@endif

	<p>
    	<a href="{{ route('events.create') }}" class="btn btn-success btn-responsive" role="button">Add new Event</a>
    </p>

    <!-- OUTDOOR EVENTS -->
    <div class="panel panel-default" >
    	<div class="panel-heading">
    		<b>Outdoor Events</b> - Search an outdoor event:
    		<select  class="selectpicker" data-live-search="true" onchange="this.options[this.selectedIndex].value && (window.location = this.options[this.selectedIndex].value);">
    		    <option data-tokens="" value=""></option>
                @foreach($outdoorEvents as $event)
                    <option data-tokens="{{$event->name}} {{$event->gender}}" value="{{route('events.edit',$event->id)}}">{{$event->name}} {{$event->gender}}</option>
                @endforeach
            </select>
    	</div>
		<div class="panel-body" style="overflow-y: scroll; height: 250px">
			<table class="table table-bordered table-sm" style="position:static;">
			  	<thead>
			    	<tr>
			      		<th>ID</th>
			      		<th>Event</th>
			      		<th>Type</th>
			      		<th>Season</th>
			      		<th>Gender</th>
			      		<th>Order</th>
			      		<th>Edit</th>

			    	</tr>
			  	</thead>

			  	<tbody>
			  		@foreach($outdoorEvents as $event)
				    	<tr>
				      		<th scope="row">{{$event->id}}</th>
				      		<td>{{$event->name}}</td>
				      		<td>{{$event->type}}</td>
				     		<td>{{$event->season}}</td>
				     		<td>{{$event->gender}}</td>
				     		<td>{{$event->order}}</td>
				      		<td>
				      			<a href="{{ route('events.edit',$event->id)}}" class="btn btn-primary btn-sm">
		  							Edit
								</a>
							</td>

				    	</tr>
			    	@endforeach
			  </tbody>
			</table>

		</div>
	</div>

	<!-- OUTDOOR EVENTS -->
    <div class="panel panel-default">
    	<div class="panel-heading">
    		<b>Indoor Events</b> - Search an indoor event:
    		<select  class="selectpicker" data-live-search="true" onchange="this.options[this.selectedIndex].value && (window.location = this.options[this.selectedIndex].value);">
    			<option data-tokens="" value=""></option>
                @foreach($indoorEvents as $event)
                    <option data-tokens="{{$event->name}} {{$event->gender}}" value="{{route('events.edit',$event->id)}}">{{$event->name}} {{$event->gender}}</option>
                @endforeach
            </select>
    	</div>
		<div class="panel-body" style="overflow-y: scroll; height: 250px">
			<table class="table table-bordered table-sm" style="position:static;">
			  	<thead>
			    	<tr>
			      		<th>Order</th>
			      		<th>Event</th>
			      		<th>Type</th>
			      		<th>Season</th>
			      		<th>Gender</th>
			      		<th>Edit</th>

			    	</tr>
			  	</thead>

			  	<tbody>
			  		@foreach($indoorEvents as $event)
				    	<tr>
				      		<th scope="row">{{$event->order}}</th>
				      		<td>{{$event->name}}</td>
				      		<td>{{$event->type}}</td>
				     		<td>{{$event->season}}</td>
				     		<td>{{$event->gender}}</td>
				      		<td>
				      			<a href="{{ route('events.edit',$event->id)}}" class="btn btn-primary btn-sm">
		  							Edit
								</a>
							</td>


				    	</tr>
			    	@endforeach
			  </tbody>
			</table>

		</div>
	</div>

	<!-- OUTDOOR EVENTS -->
    <div class="panel panel-default">
    	<div class="panel-heading">
    		<b>Cross Country Events</b> - Search a XC event:
    		<select  class="selectpicker" data-live-search="true" onchange="this.options[this.selectedIndex].value && (window.location = this.options[this.selectedIndex].value);">
    		    <option data-tokens="" value=""></option>
                @foreach($ccEvents as $event)
                    <option data-tokens="{{$event->name}} {{$event->gender}}" value="{{route('events.edit',$event->id)}}">{{$event->name}} {{$event->gender}}</option>
                @endforeach
            </select>
    	</div>
		<div class="panel-body" style="overflow-y: scroll; height: 250px">
			<table class="table table-bordered table-sm" style="position:static;">
			  	<thead>
			    	<tr>
			      		<th>ID</th>
			      		<th>Event</th>
			      		<th>Type</th>
			      		<th>Season</th>
			      		<th>Gender</th>
			      		<th>Order</th>
			      		<th>Edit</th>

			    	</tr>
			  	</thead>

			  	<tbody>
			  		@foreach($ccEvents as $event)
				    	<tr>
				      		<th scope="row">{{$event->id}}</th>
				      		<td>{{$event->name}}</td>
				      		<td>{{$event->type}}</td>
				     		<td>{{$event->season}}</td>
				     		<td>{{$event->gender}}</td>
				     		<td>{{$event->order}}</td>
				      		<td>
				      			<a href="{{ route('events.edit',$event->id)}}" class="btn btn-primary btn-sm">
		  							Edit
								</a>
							</td>


				    	</tr>
			    	@endforeach
			  </tbody>
			</table>

		</div>
	</div>
@endsection