routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();
//Redirect to closed view
Route::middleware(['closed'])->group(function () {
	/*
	|--------------------------------------------------------------------------
	| HOME route
	|--------------------------------------------------------------------------
	|
	*/

	Route::get('/', 'HomeController@index')->name('home');


	Route::post('/search/show', 'HomeController@searchShow')->name('search.show');
	Route::post('/search', 'HomeController@search')->name('search');

	/*
	|--------------------------------------------------------------------------
	| Athletes Routes
	|--------------------------------------------------------------------------
	|
	*/
	Route::get('/athlete/{athlete}', 'AthleteController@show')->name('athlete.show');

	/*
	|--------------------------------------------------------------------------
	| Competitions Routes
	|--------------------------------------------------------------------------
	|
	*/
	Route::get('/competition/{competition}', 'CompetitionController@show')->name('competition.show');
	Route::get('/calendar', 'CompetitionController@showCalendar')->name('competition.calendar');

	/*
	|--------------------------------------------------------------------------
	| Clubs Routes
	|--------------------------------------------------------------------------
	|
	*/
	Route::get('/club/{club}', 'ClubController@show')->name('club.show');


	/*
	|--------------------------------------------------------------------------
	| Records Routes
	|--------------------------------------------------------------------------
	|
	*/
	/* GET events for national record form */
	Route::post('/records/nationals/history/events', 'RecordController@getEvents')->name('record.getEvents');
	Route::get('/records/nationals/history', 'RecordController@showNRsHistory')->name('record.showNRsHistory')->middleware('role:admin');
	Route::post('/records/nationals/history', 'RecordController@searchNRsHistory')->name('record.searchNRsHistory')->middleware('role:admin');
	Route::get('/records/nationals', 'RecordController@showNRs')->name('record.showNRs');
	Route::post('/records/nationals', 'RecordController@searchNRs')->name('record.searchNRs');


	/*
	|--------------------------------------------------------------------------
	| Top-List Routes
	|--------------------------------------------------------------------------
	|
	*/
	Route::get('/toplist', 'TopListController@show')->name('toplist.show');
	Route::post('/toplist', 'TopListController@search')->name('toplist.search');
	Route::post('/toplist/events', 'TopListController@getEvents')->name('toplist.getEvents');


	/*
	|--------------------------------------------------------------------------
	| Score-List Routes
	|--------------------------------------------------------------------------
	|
	*/
	Route::get('/scorelist', 'ScoreListController@show')->name('scorelist.show');
	Route::post('/scorelist', 'ScoreListController@search')->name('scorelist.search');


	/*
	|--------------------------------------------------------------------------
	| All-Time Performance Routes
	|--------------------------------------------------------------------------
	|
	*/
	Route::get('/alltime', 'AllTimeController@show')->name('alltime.show');
	Route::post('/alltime', 'AllTimeController@search')->name('alltime.search');
	Route::post('/alltime/events', 'AllTimeController@getEvents')->name('alltime.getEvents');

	/*
	|--------------------------------------------------------------------------
	| Contact us Routes
	|--------------------------------------------------------------------------
	|
	*/
	Route::get('/contact-us', 'ContactController@show')->name('contact.show');
	Route::post('/contact-us', 'ContactController@send')->name('contact.send');


	/*
	|--------------------------------------------------------------------------
	| ADMIN DASHBOARD Routes
	|--------------------------------------------------------------------------
	|	resource routes for CRUD
	|	all the controllers are in App/Dashboard
	*/

	//For admins and moderators
	Route::middleware(['auth','role:admin,moderator'])->group(function () {
		Route::get('dashboard', function () {
		    return view('dashboard/home');
		});
		Route::resource('dashboard/club', 'Dashboard\ClubCrudController', ['except' => ['show', 'destroy']]);
		Route::resource('dashboard/athlete', 'Dashboard\AthleteCrudController', ['except' => ['show', 'destroy']]);
		Route::resource('dashboard/series', 'Dashboard\SeriesCrudController', ['except' => ['show', 'destroy']]);
		Route::resource('dashboard/competition', 'Dashboard\CompetitionCrudController', ['except' => ['show', 'destroy']]);
		Route::resource('dashboard/result', 'Dashboard\ResultCrudController', ['except' => ['show']]);
		Route::resource('dashboard/image', 'Dashboard\ImageCrudController', ['except' => ['show', 'destroy']]);
		Route::resource('dashboard/video', 'Dashboard\VideoCrudController', ['except' => ['show', 'destroy']]);

		Route::post('/dashboard/result/events', 'Dashboard\ResultCrudController@getEvents')->name('results.getEvents');
		Route::post('/dashboard/result/dates', 'Dashboard\ResultCrudController@getDates')->name('results.getDates');

		Route::get('/dashboard/result/createRace', 'Dashboard\ResultCrudController@createRace')->name('result.createRace');
		Route::post('/dashboard/result/createRace', 'Dashboard\ResultCrudController@storeRace')->name('result.storeRace');

	});
	//For admins only
	Route::middleware(['auth','role:admin'])->group(function () {
		Route::resource('dashboard/events', 'Dashboard\EventCrudController', ['except' => ['show','destroy']]);
		Route::resource('dashboard/users', 'Dashboard\UserCrudController', ['except' => ['create','store','show']]);
		//PENDING AND PUBLISHING
		Route::get('dashboard/pending', 'Dashboard\PendingController@index')->name('pending.index');
		Route::post('dashboard/pending', 'Dashboard\PendingController@publish')->name('pending.publish');

		//COMMANDS
		Route::get('dashboard/commands', 'Dashboard\CommandController@index')->name('commands.index');
		Route::get('dashboard/commands/fixyearinathletes', 'Dashboard\CommandController@fixYearInAthletes')->name('commands.fixYearInAthletes');
		Route::get('dashboard/commands/fixageinresults', 'Dashboard\CommandController@fixAgeInResults')->name('commands.fixAgeInResults');
		Route::post('dashboard/commands/refreshrecordbyevent', 'Dashboard\CommandController@refreshRecordByEvent')->name('commands.refreshRecordByEvent');

	});
});

app/Athlete.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;
use App\Age;
use App\Traits\Linkable;
use App\Traits\Statusable;

class Athlete extends Model
{

    use Linkable;
    use Statusable;

    /**********************************
    //  Relationships
    ***********************************/

    public function club()
  	{
  		return $this->belongsTo('App\Club', 'club_id');
  	}

    public function links()
    {
      return $this->morphMany('App\Link', 'linkable');
    }

    public function results()
    {
      return $this->hasMany('App\Result')->published();
    }

		public function videos()
		{
			return $this->morphToMany('App\Video', 'videable');
		}

		public function images()
		{
			return $this->morphToMany('App\Image', 'imageable');
		}

    public function relayResults()
    {
      return $this->BelongsToMany('App\Result', 'relay_athletes', 'athlete_id', 'result_id')->published();
    }

    /****************************************************/
    //    Search Scope
    /****************************************************/
    public function scopeSearch($query,$search){

      // split on 1+ whitespace & ignore empty (eg. trailing space)
      $searchValues = preg_split('/\s+/', $search, -1, PREG_SPLIT_NO_EMPTY);

      return $query->where(function ($q) use ($searchValues) {
        foreach ($searchValues as $value) {
          $q->orWhere('first_name', 'like', "%{$value}%")
          ->orWhere('last_name','like', "%{$value}%");
        }
      })->orderBy('first_name','asc');

    }

    /**********************************
    //  Functions that return results
    ***********************************/

    public function getAgeAttribute(): string
    {
      $date = new \DateTime('now');
      $difference = $date->diff(new \DateTime($this->dob));
      return $difference->format('%y');
    }

    public function getNameAttribute(): string
    {
      return $this->first_name . ' ' . $this->last_name;
    }

    public function getBirthAttribute(): string
    {
      if($this->dob){
        return date('d.m.Y', strtotime($this->dob));
      }elseif($this->year=="1000"){
        return "Relay Team";
      }elseif($this->year=="1700"){
        return "Unkown Date of Birth";
      }else{
        return $this->year;
      }

    }

    public function isU16()
    {
      $age = Age::where('category', 'u16')->first();
      return $this->age >= $age->min && $this->age <= $age->max;
    }

    public function isU18()
    {
      $age = Age::where('category', 'u18')->first();
      return $this->age >= $age->min && $this->age <= $age->max;
    }

    public function isU20()
    {
      $age = Age::where('category', 'u20')->first();
      return $this->age >= $age->min && $this->age <= $age->max;
    }

    public function isU23()
    {
      $age = Age::where('category', 'u23')->first();
      return $this->age >= $age->min && $this->age <= $age->max;
    }

    public function isMale()
    {
      return $this->gender=='male';
    }

    public function isFemale()
    {
      return $this->gender=='female';
    }

    public function scopeMale($query)
    {
      return $query->where('gender', 'male')->get();
    }

    public function scopeFemale($query)
    {
      return $query->where('gender', 'female')->get();
    }


    /*
    ** Returns a collection of all results of this athlete over the years
    ** partitioned based on events ($key = $event_id , $value= collection of $Results )
    */
    public function getAllResultsByEvent()
    {

      //Get all results of athlete
      $results = $this->results->sortBy('date');

      //Find events in which athlete has results
      $events = $this->uniqueEvents($results);

      //create a collection with keys the event_id and values the Result records
      $collection=collect([]);
      foreach($events as $event){
        $eventResults = $results->where('event_id',$event);
        $collection = $collection->put($event, $eventResults);
      }

      return $collection;
    }

    /*
    ** Returns a collection of all results of this athlete
    ** in competition of the series= $series
    ** that finished in position= $position
    */
    public function countPlaces($series,$position)
    {
      $competitions = $series->competitions()->get();
      $race = "Τελικός";

      $count = 0;
      foreach($competitions as $competition){
        $results = $competition->results()->where('athlete_id',$this->id)
                                          ->where('overall','LIKE',$position)
                                          ->get();

        foreach ($results as $result) {
          if  (starts_with($result->race, 'Τελικός')){
            $count += 1;
          }

        }
      }

      return $count;
    }




    /**********************************
    //  Functions that return records
    //  -----     PB      -----
    ***********************************/

    /*
    ** Returns a collection of all PBs of this athlete over the years
    ** partitioned based on events ($key = $event_id , $value= collection of $PBs )
    */
    public function getAllPbs()
    {
      //Get PB record ID
      $record = Record::where('acronym','PB')->first();
      $recordId = $record->id;

      //Get all PBs of athlete
      $pbs = Result::whereHas('records',function ($query) use ($recordId) {
        $query->where('record_id','=', $recordId);
      })->where('athlete_id',$this->id)->get();

      //Find events in which athlete has pbs
      $events = $this->uniqueEvents($pbs);

      //create a collection with keys the event_id and values the PBs
      $collection=collect([]);
      foreach($events as $event){
        $eventPbs = $pbs->where('event_id',$event);
        $collection = $collection->put($event, $eventPbs);
      }

      return $collection;
    }

    /*
    ** Returns a collection of all PBs of this athlete RIGHT NOW
    ** partitioned based on events ($key = $event_id , $value= PB )
    */
    public function getPbs()
    {
      //Get PB record ID
      $record = Record::where('acronym','PB')->first();
      $recordId = $record->id;

      //Get all PBs of athlete
      $pbs = Result::whereHas('records',function ($query) use ($recordId) {
        $query->where('record_id','=', $recordId);
      })->where('athlete_id',$this->id)->get();

      //Find events in which athlete has pbs
      $events = $this->uniqueEvents($pbs);

      //create a collection with keys the event_id and values the PBs
      $collection=collect([]);
      foreach($events as $event){
        //All PBs made for the event by the athlete
        $eventPbs = $pbs->where('event_id',$event);
        //Find best PB
        $eventPb = $this->bestRecord(Event::find($event),$eventPbs);

        //Add PB to collection with key the event id
        $collection = $collection->put($event, $eventPb);
      }

      return $collection;
    }

    /*
    ** Returns a collection of all PBs of this athlete for a specific EVENT over
    ** the years
    */
    public function getPbsEvent($event)
    {
      //Get PB record ID
      $record = Record::where('acronym','PB')->first();
      $recordId = $record->id;

      //Get all pbs of athlete on the $event
      $pbs = Result::whereHas('records',function ($query) use ($recordId) {
        $query->where('record_id','=', $recordId);
      })->where('athlete_id',$this->id)->where('event_id',$event->id)->get();

      return $pbs;
    }

    /*
    // Returns THE PB of this athlete for a specific EVENT
    */
    public function getPb($event, $date = null)
    {

      if(!$date){
        $date = Carbon::now();
      }

      //Get PB record ID
      $record = Record::where('acronym','PB')->first();
      $recordId = $record->id;

      //Get all PBs of athlete for this event
      $pbs = Result::whereHas('records',function ($query) use ($recordId) {
        $query->where('record_id','=', $recordId);
      })->where('athlete_id',$this->id)->where('event_id',$event->id)->whereBetween('date',['1000-01-01' ,$date])->get();

      //Find best PB based on event type
      $pb = $this->bestRecord($event,$pbs);
      return $pb;
    }





    /**********************************
    //  Functions that return records
    //  -----     SB      -----
    ***********************************/

    /*
    // Returns a collection of all SBs of this athlete for a specific YEAR
    */
    public function getAllSBs($year)
    {
      //Get SB record ID
      $record = Record::where('acronym','SB')->first();
      $recordId = $record->id;

      //Get SB of athlete for the year
      $sbs = Result::whereHas('records',function ($query) use ($recordId) {
        $query->where('record_id','=', $recordId);
      })->where('athlete_id',$this->id)->where(DB::raw('YEAR(date)'), '=',$year)->get();

      return $sbs;
    }


    /*
    // Returns a collection of THE BEST SBs of this athlete for a specific YEAR
    */
    public function getSBs($year)
    {
      //Get SB record ID
      $record = Record::where('acronym','SB')->first();
      $recordId = $record->id;

      //Get SB of athlete for the year
      $sbs = Result::whereHas('records',function ($query) use ($recordId) {
        $query->where('record_id','=', $recordId);
      })->where('athlete_id',$this->id)->where(DB::raw('YEAR(date)'), '=',$year)->get();

      //Find events in which athlete has pbs
      $events = $this->uniqueEvents($sbs);

      //create a collection with keys the event_id and values the SBs
      $collection=collect([]);
      foreach($events as $event){
        //All SBs made for the event by the athlete
        $eventSbs = $sbs->where('event_id',$event);
        //Find best SB
        $eventSb = $this->bestRecord(Event::find($event),$eventSbs);

        //Add PB to collection with key the event id
        $collection = $collection->put($event, $eventSb);
      }

      return $collection;
    }

    /*

resources/views/dashboard/pending/index.blade.php
@extends('layouts.dashboard')

@section('content')
{!! Form::open(array('route' => 'pending.publish','class' => 'form-horizontal'))!!}

   	{{ csrf_field() }}

	<div class="panel panel-default">
		<div class="panel-heading">Athletes Pending</div>
		<div class="panel-body">
			<label>Publish All Athletes</label>
			<input type="checkbox" id="checkAllAthletes">
			<div class="table-responsive">
			<table class="table table-bordered table-sm" style="position:static;">
			  	<thead>
			    	<tr>
			    		<th>Publish</th>
			      		<th>ID</th>
			      		<th>First Name</th>
			      		<th>Last Name</th>
			      		<th>Date of Birth</th>
			      		<th>Gender</th>
			      		<th>Club</th>
			      		<th>Picture</th>
			      		<th>Edit</th>
			    	</tr>
			  	</thead>

			  	<tbody>
			  		@foreach($athletes as $athlete)
				    	<tr>
				    		<td><input class="athletes" name="athletes[]" type="checkbox" value="{{$athlete->id}}"></td>
				      		<th scope="row">{{$athlete->id}}</th>
				      		<td>{{$athlete->first_name}}</td>
				      		<td>{{$athlete->last_name}}</td>
				     		<td>{{$athlete->birth}}</td>
				     		<td>{{$athlete->gender}}</td>
				     		<td>{{optional($athlete->club)->name}}</td>
				      		<td><img src="/storage/{{ $athlete->picture }}" class="img-responsive" style="max-width: 10vw; max-height: 10vh;"></td>
				      		<td>
				      			<a href="{{ route('athlete.edit',$athlete->id)}}" class="btn btn-primary btn-sm">
		  							Edit
								</a>
							</td>

				    	</tr>
			    	@endforeach
			  </tbody>
			</table>
			</div>
		</div>
	</div>
    <button type="submit" class="btn btn-success" style="margin-bottom: 10px;">Publish</button>

	<div class="panel panel-default">
		<div class="panel-heading">Competitions Pending</div>
		<div class="panel-body">
			<label>Publish All Competitions</label>
			<input type="checkbox" id="checkAllCompetitions">
			<div class="table-responsive">
			<table class="table table-bordered table-sm" style="position:static;">
			  	<thead>
			    	<tr>
			    		<th>Publish</th>
			      		<th>ID</th>
			      		<th>Name</th>
			      		<th>Start Date</th>
			      		<th>Finish Date</th>
			      		<th>Country</th>
			      		<th>City</th>
			      		<th>Venue</th>
			      		<th>Edit</th>
			    	</tr>
			  	</thead>

			  	<tbody>
			  		@foreach($competitions as $competition)
				    	<tr>
				    		<td><input class="competitions" name="competitions[]" type="checkbox" value="{{$competition->id}}"></td>
				      		<th scope="row">{{$competition->id}}</th>
				      		<td>{{$competition->name}}</td>
				      		<td>{{$competition->date_start}}</td>
				     		<td>{{$competition->date_finish}}</td>
				      		<td>{{$competition->country}}</td>
				      		<td>{{$competition->city}}</td>
				      		<td>{{$competition->venue}}</td>
				      		<td>
				      			<a href="{{ route('competition.edit',$competition->id)}}" class="btn btn-primary btn-sm">
		  							Edit
								</a>
							</td>

				    	</tr>
			    	@endforeach
			  </tbody>
			</table>
			</div>
		</div>
	</div>
    <button type="submit" class="btn btn-success" style="margin-bottom: 10px;">Publish</button>
	<div class="panel panel-default">
		<div class="panel-heading">Results Pending</div>
		<div class="panel-body">
			<label>Publish All Results</label>
			<input type="checkbox" id="checkAllResults">
			<div class="table-responsive">
			<table class="table table-bordered table-sm table-responsive" style="position:static;">
			  	<thead>
			    	<tr>
			    		<th>Publish</th>
			      		<th>ID</th>
			      		<th>Position</th>
			      		<th>Athlete</th>
			      		<th>Competition</th>
			      		<th>Race</th>
			      		<th>Date</th>
			      		<th>Event</th>
			      		<th>Mark</th>
			      		<th>Score</th>
			      		<th>Edit</th>
			    	</tr>
			  	</thead>
			  		@foreach($results as $result)
				    	<tr>
				    		<td><input class="results" name="results[]" type="checkbox" value="{{$result->id}}"></td>
				      		<th scope="row">{{$result->id}}</th>
				      		<td>{{$result->position}}</td>
				      		<td>{{$result->athlete->first_name}} {{$result->athlete->last_name}}</td>
				     		<td>{{$result->competition->name}}</td>
				      		<td>{{$result->race}}</td>
				      		<td>{{$result->date}}</td>
				      		<td>{{$result->event->name}}</td>
				      		<td>{{$result->mark}}</td>
				      		<td>{{$result->score}}</td>
				      		<td>
				      			<a href="{{ route('result.edit',$result->id)}}" class="btn btn-primary btn-sm">
		  							Edit
								</a>
							</td>

				    	</tr>
			    	@endforeach
			  	<tbody>

			  </tbody>
			</table>
			</div>
		</div>
	</div>
    <button type="submit" class="btn btn-success" style="margin-bottom: 10px;">Publish</button>

{!! Form::close() !!}

@endsection
@section('scripts')
<script type="text/javascript">
	$("#checkAllAthletes").click(function () {
    	$("input.athletes").not(this).prop('checked', this.checked);
 	});

 	$("#checkAllCompetitions").click(function () {
    	$("input.competitions").not(this).prop('checked', this.checked);
 	});

 	$("#checkAllResults").click(function () {
    	$("input.results").not(this).prop('checked', this.checked);
 	});
</script>
@endsection